### ISSUE TITLE
API feedback / suggestions

### ISSUE THREAD

**Issue by alexkof** [wavesplatform/swagger-api-design#1]
Post API suggestions here.

**Comment by beregovoy68** [comment]
Are you guys sure that **/addresses/{address}** should return Waves balance AND a list of aliases? Does it make sense to split that into two independent operations?

**/addresses/{address}/transactions:**
I would suggest using heightFrom and heightTo parameters instead of using timestamps.

**/addresses/{address}/transactions/unconfirmed**
Please add paging here as well. Offset and Limit parameters should work ok here.

**/assets/{assetId}**
I think that method should return actual asset data like total tokens supply (including issue, reissue, and burn). All the rest like transaction list in chronological order should be returned by a separate method.

**/assets/{assetId}/distribution**
What about paging here as well?

New transactions API is *awesome*. Adds more structure and clarity.

**General feedback**
New API doesn't address the balances issue. When there are thousands of assets you don't know how to interpret asset balance if it's just an integer. You need to know asset precision to translate integers to actual values.
I can think of two possible solutions for that
1. All balances are rational numbers already converted by backend. It's not clear from API docs whether you chose this way or not.
2. You use Money pattern from Fowler's EAA book. Which basically means that every balance coming from backend is an object, which contains integer balance value, precision, asset name and asset id.

**Comment by beregovoy68** [comment]
When it comes to asset amounts relying on numbers is not an option. Javascript doesn't have integer numbers, it just pretends they exist. That's why it doesn't matter how you transfer numbers as integers or as floating point numbers. In both ways you can lose precision (java's longs are 2^63):
https://stackoverflow.com/questions/307179/what-is-javascripts-highest-integer-value-that-a-number-can-go-to-without-losin

One of the possible solutions is to transfer amounts as strings and convert them on javascript side using a third-party library that deals with big numbers like Decimal.js which can parse string values.

**Comment by xenohunter** [comment]
Yep, we're already thinking about this. 99% is that we will stick to string values.

**Comment by xenohunter** [comment]
The repo is not very active now thus I'm closing the issue.
